# Generated by Django 4.0.3 on 2022-03-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('office_location', models.CharField(max_length=100)),
                ('visitor_host', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('visitor_status', models.CharField(max_length=100)),
            ],
        ),
    ]
